# Generated by Django 3.2.13 on 2022-05-23 15:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeerBrewery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('web', models.URLField(blank=True, verbose_name='Web Address')),
            ],
        ),
        migrations.CreateModel(
            name='BeersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_type', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('data_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('brewery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='birrita_app.beerbrewery')),
            ],
        ),
    ]
