# Generated by Django 3.2.13 on 2022-05-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birrita_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beerslist',
            name='price_hh',
            field=models.DecimalField(blank=True, decimal_places=0, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='beerslist',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10),
        ),
    ]
