# Generated by Django 3.2.13 on 2022-05-25 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birrita_app', '0002_auto_20220524_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerslist',
            name='brewery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='birrita_app.beerbrewery'),
        ),
    ]
