# Generated by Django 3.2.13 on 2022-05-26 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birrita_app', '0003_alter_beerslist_brewery'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreweryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brewery', models.CharField(max_length=120)),
                ('web', models.URLField(blank=True, verbose_name='Web Address')),
            ],
        ),
        migrations.RenameField(
            model_name='beerslist',
            old_name='beer_type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='beerslist',
            name='brewery',
        ),
        migrations.AlterField(
            model_name='beerslist',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beerslist',
            name='price_hh',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='BeerBrewery',
        ),
        migrations.AddField(
            model_name='brewerylist',
            name='beer_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='birrita_app.beerslist'),
        ),
    ]
