# Generated by Django 3.2.13 on 2022-05-26 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birrita_app', '0004_auto_20220526_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreweriesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('web', models.URLField(blank=True, verbose_name='Web Address')),
            ],
        ),
        migrations.RemoveField(
            model_name='brewerylist',
            name='web',
        ),
        migrations.AlterField(
            model_name='brewerylist',
            name='brewery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='birrita_app.brewerieslist'),
        ),
    ]
