# Generated by Django 3.2.13 on 2022-05-26 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('birrita_app', '0005_auto_20220526_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beerslist',
            name='data_date',
        ),
        migrations.RemoveField(
            model_name='beerslist',
            name='price',
        ),
        migrations.RemoveField(
            model_name='beerslist',
            name='price_hh',
        ),
        migrations.AddField(
            model_name='brewerylist',
            name='data_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='brewerylist',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='brewerylist',
            name='price_hh',
            field=models.IntegerField(default=0),
        ),
    ]
