# Generated by Django 3.2.13 on 2022-05-26 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birrita_app', '0006_auto_20220526_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brewerylist',
            options={'ordering': ['-data_date']},
        ),
    ]
