# Generated by Django 3.2.13 on 2022-05-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birrita_app', '0008_alter_brewerieslist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beerslist',
            options={'ordering': ['-name']},
        ),
    ]
